import Project from '../models/Project.js';
import Contractor from '../models/Contractor.js';

const seedProjects = async () => {
    try {
        await Project.deleteMany({});

        const projects = [
            {
                region: 'Region IV-B',
                legislative_district: 'PALAWAN (THIRD LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Palawan 3rd District Engineering Office',
                project_id: 'P00824759LZ',
                project_name: 'Construction of Babuyan River Flood Control Structure Downstream (RS), Palawan',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 118.89245000,
                latitude: 9.99653000,
                contract_id: '24EG0058',
                approved_budget: 17963475,
                contract_cost: 17961569.07,
                start_date: new Date('2024-02-15'),
                funding_year: 2024,
                completion_date_actual: new Date('2024-05-23'),
                contractor_id: null,
                contractor_name: 'AZARRAGA CONSTRUCTION',
                status: 'finished',
                risk_score: 15,
                is_flagged: false
            },
            {
                region: 'NCR',
                legislative_district: 'MANILA (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Manila 1st District Engineering Office',
                project_id: 'P00912345AB',
                project_name: 'Pasig River Flood Control Wall Construction, Manila',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 120.98422000,
                latitude: 14.59951000,
                contract_id: '24EG0100',
                approved_budget: 25000000,
                contract_cost: 24850000,
                start_date: new Date('2024-01-10'),
                funding_year: 2024,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'ABC CONSTRUCTION COMPANY',
                status: 'ongoing',
                risk_score: 25,
                is_flagged: false
            },
            {
                region: 'Region IV-A',
                legislative_district: 'LAGUNA (SECOND LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Laguna 2nd District Engineering Office',
                project_id: 'P00789123CD',
                project_name: 'San Pedro Creek Drainage Improvement Project',
                type_of_work: 'River Channel Improvement',
                infrastructure_type: 'Flood Control Structures',
                longitude: 121.05750000,
                latitude: 14.35917000,
                contract_id: '24EG0088',
                approved_budget: 32000000,
                contract_cost: 31800000,
                start_date: new Date('2023-11-01'),
                funding_year: 2023,
                completion_date_actual: new Date('2024-03-15'),
                contractor_id: null,
                contractor_name: 'ABC CONSTRUCTION COMPANY',
                status: 'finished',
                risk_score: 20,
                is_flagged: false
            },
            {
                region: 'Region III',
                legislative_district: 'PAMPANGA (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Pampanga 1st District Engineering Office',
                project_id: 'P00654321EF',
                project_name: 'Pampanga River Flood Control Structure Phase 2',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 120.59083000,
                latitude: 15.06667000,
                contract_id: '23EG0055',
                approved_budget: 45000000,
                contract_cost: 44200000,
                start_date: new Date('2023-06-01'),
                funding_year: 2023,
                completion_date_actual: new Date('2023-12-20'),
                contractor_id: null,
                contractor_name: 'XYZ INFRASTRUCTURE BUILDERS',
                status: 'finished',
                risk_score: 12,
                is_flagged: false
            },
            {
                region: 'Region III',
                legislative_district: 'PAMPANGA (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Pampanga 1st District Engineering Office',
                project_id: 'P00543210GH',
                project_name: 'San Fernando Flood Control Channel Improvement',
                type_of_work: 'Drainage System Improvement',
                infrastructure_type: 'Flood Control Structures',
                longitude: 120.68611000,
                latitude: 15.03167000,
                contract_id: '23EG0044',
                approved_budget: 28000000,
                contract_cost: 27500000,
                start_date: new Date('2023-04-15'),
                funding_year: 2023,
                completion_date_actual: new Date('2023-10-30'),
                contractor_id: null,
                contractor_name: 'XYZ INFRASTRUCTURE BUILDERS',
                status: 'finished',
                risk_score: 18,
                is_flagged: false
            },
            {
                region: 'Region IV-A',
                legislative_district: 'BATANGAS (SECOND LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Batangas 2nd District Engineering Office',
                project_id: 'P00432109IJ',
                project_name: 'Calumpang River Flood Control Structure',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 121.05806000,
                latitude: 13.75944000,
                contract_id: '24EG0123',
                approved_budget: 38000000,
                contract_cost: 37500000,
                start_date: new Date('2024-03-01'),
                funding_year: 2024,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'XYZ INFRASTRUCTURE BUILDERS',
                status: 'ongoing',
                risk_score: 22,
                is_flagged: false
            },
            {
                region: 'Region V',
                legislative_district: 'ALBAY (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Albay 1st District Engineering Office',
                project_id: 'P00321098KL',
                project_name: 'Bicol River Flood Control Wall Phase 1',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 123.59556000,
                latitude: 13.13333000,
                contract_id: '22EG0099',
                approved_budget: 50000000,
                contract_cost: 22000000,
                start_date: new Date('2022-01-15'),
                funding_year: 2022,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'PHANTOM BUILDERS CORP',
                status: 'ongoing',
                risk_score: 95,
                is_flagged: true
            },
            {
                region: 'Region V',
                legislative_district: 'ALBAY (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Albay 1st District Engineering Office',
                project_id: 'P00210987MN',
                project_name: 'Legazpi City Flood Control Structure',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 123.74222000,
                latitude: 13.13917000,
                contract_id: '22EG0100',
                approved_budget: 28000000,
                contract_cost: 25000000,
                start_date: new Date('2022-03-01'),
                funding_year: 2022,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'PHANTOM BUILDERS CORP',
                status: 'ongoing',
                risk_score: 92,
                is_flagged: true
            },
            {
                region: 'Region V',
                legislative_district: 'ALBAY (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Albay 1st District Engineering Office',
                project_id: 'P00109876OP',
                project_name: 'Tabaco River Channel Improvement',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 123.72444000,
                latitude: 13.35722000,
                contract_id: '23EG0077',
                approved_budget: 35000000,
                contract_cost: 28000000,
                start_date: new Date('2023-02-10'),
                funding_year: 2023,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'PHANTOM BUILDERS CORP',
                status: 'ongoing',
                risk_score: 88,
                is_flagged: true
            },
            {
                region: 'Region V',
                legislative_district: 'ALBAY (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Albay 1st District Engineering Office',
                project_id: 'P00098765QR',
                project_name: 'Ligao Flood Control Project',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 123.54028000,
                latitude: 13.24139000,
                contract_id: '23EG0078',
                approved_budget: 40000000,
                contract_cost: 20000000,
                start_date: new Date('2023-05-01'),
                funding_year: 2023,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'PHANTOM BUILDERS CORP',
                status: 'ongoing',
                risk_score: 96,
                is_flagged: true
            },
            {
                region: 'Region VI',
                legislative_district: 'ILOILO (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Iloilo 1st District Engineering Office',
                project_id: 'P00987654ST',
                project_name: 'Iloilo River Flood Control Wall',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 122.56417000,
                latitude: 10.69694000,
                contract_id: '21EG0055',
                approved_budget: 45000000,
                contract_cost: 45000000,
                start_date: new Date('2021-06-01'),
                funding_year: 2021,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'SHADOW CONSTRUCTION INC',
                status: 'ongoing',
                risk_score: 98,
                is_flagged: true
            },
            {
                region: 'Region VI',
                legislative_district: 'ILOILO (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Iloilo 1st District Engineering Office',
                project_id: 'P00876543UV',
                project_name: 'Jaro River Channel Improvement',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 122.54861000,
                latitude: 10.71667000,
                contract_id: '21EG0056',
                approved_budget: 38000000,
                contract_cost: 38000000,
                start_date: new Date('2021-08-15'),
                funding_year: 2021,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'SHADOW CONSTRUCTION INC',
                status: 'ongoing',
                risk_score: 97,
                is_flagged: true
            },
            {
                region: 'Region VI',
                legislative_district: 'ILOILO (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Iloilo 1st District Engineering Office',
                project_id: 'P00765432WX',
                project_name: 'Molo River Flood Control',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 122.57083000,
                latitude: 10.71361000,
                contract_id: '22EG0022',
                approved_budget: 42000000,
                contract_cost: 42000000,
                start_date: new Date('2022-01-10'),
                funding_year: 2022,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'SHADOW CONSTRUCTION INC',
                status: 'ongoing',
                risk_score: 96,
                is_flagged: true
            },
            {
                region: 'Region VI',
                legislative_district: 'ILOILO (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Iloilo 1st District Engineering Office',
                project_id: 'P00654321YZ',
                project_name: 'Passi City Flood Control Structure',
                type_of_work: 'River Channel Improvement',
                infrastructure_type: 'Flood Control Structures',
                longitude: 122.65417000,
                latitude: 11.10917000,
                contract_id: '22EG0023',
                approved_budget: 30000000,
                contract_cost: 18000000,
                start_date: new Date('2022-04-01'),
                funding_year: 2022,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'SHADOW CONSTRUCTION INC',
                status: 'ongoing',
                risk_score: 94,
                is_flagged: true
            },
            {
                region: 'Region VI',
                legislative_district: 'ILOILO (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Iloilo 1st District Engineering Office',
                project_id: 'P00543210AA',
                project_name: 'Miagao River Channel Project',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 122.23528000,
                latitude: 10.64417000,
                contract_id: '23EG0033',
                approved_budget: 35000000,
                contract_cost: 25000000,
                start_date: new Date('2023-01-20'),
                funding_year: 2023,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'SHADOW CONSTRUCTION INC',
                status: 'ongoing',
                risk_score: 93,
                is_flagged: true
            },
            {
                region: 'Region VI',
                legislative_district: 'ILOILO (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Iloilo 1st District Engineering Office',
                project_id: 'P00432109BB',
                project_name: 'Oton River Flood Control',
                type_of_work: 'River Channel Improvement',
                infrastructure_type: 'Flood Control Structures',
                longitude: 122.48778000,
                latitude: 10.69111000,
                contract_id: '23EG0034',
                approved_budget: 28000000,
                contract_cost: 28000000,
                start_date: new Date('2023-03-15'),
                funding_year: 2023,
                completion_date_actual: new Date('2023-12-20'),
                contractor_id: null,
                contractor_name: 'SHADOW CONSTRUCTION INC',
                status: 'finished',
                risk_score: 45,
                is_flagged: false
            },
            {
                region: 'Region VII',
                legislative_district: 'CEBU (SECOND LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Cebu 2nd District Engineering Office',
                project_id: 'P00321098CC',
                project_name: 'Mandaue River Flood Control Wall',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 123.93806000,
                latitude: 10.32306000,
                contract_id: '21EG0044',
                approved_budget: 55000000,
                contract_cost: 28000000,
                start_date: new Date('2021-02-01'),
                funding_year: 2021,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'QUICK MONEY BUILDERS',
                status: 'ongoing',
                risk_score: 99,
                is_flagged: true
            },
            {
                region: 'Region VII',
                legislative_district: 'CEBU (SECOND LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Cebu 2nd District Engineering Office',
                project_id: 'P00210987DD',
                project_name: 'Lapu-Lapu Flood Control Structure',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 123.94917000,
                latitude: 10.31028000,
                contract_id: '22EG0011',
                approved_budget: 48000000,
                contract_cost: 24000000,
                start_date: new Date('2022-01-15'),
                funding_year: 2022,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'QUICK MONEY BUILDERS',
                status: 'ongoing',
                risk_score: 98,
                is_flagged: true
            },
            {
                region: 'Region VII',
                legislative_district: 'CEBU (SECOND LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Cebu 2nd District Engineering Office',
                project_id: 'P00109876EE',
                project_name: 'Talisay River Channel Improvement',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 123.84667000,
                latitude: 10.24444000,
                contract_id: '23EG0011',
                approved_budget: 42000000,
                contract_cost: 23000000,
                start_date: new Date('2023-02-01'),
                funding_year: 2023,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'QUICK MONEY BUILDERS',
                status: 'ongoing',
                risk_score: 97,
                is_flagged: true
            },
            {
                region: 'Region VIII',
                legislative_district: 'LEYTE (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Leyte 1st District Engineering Office',
                project_id: 'P00098765FF',
                project_name: 'Tacloban Flood Control Structure Phase 1',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 124.99417000,
                latitude: 11.24306000,
                contract_id: '22EG0055',
                approved_budget: 45000000,
                contract_cost: 43200000,
                start_date: new Date('2022-03-01'),
                funding_year: 2022,
                completion_date_actual: new Date('2022-12-15'),
                contractor_id: null,
                contractor_name: 'RELIABLE FLOOD CONTROL SERVICES',
                status: 'finished',
                risk_score: 20,
                is_flagged: false
            },
            {
                region: 'Region VIII',
                legislative_district: 'LEYTE (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Leyte 1st District Engineering Office',
                project_id: 'P00987654GG',
                project_name: 'Tacloban Flood Control Structure Phase 2',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 125.00111000,
                latitude: 11.25000000,
                contract_id: '23EG0044',
                approved_budget: 48000000,
                contract_cost: 46500000,
                start_date: new Date('2023-01-10'),
                funding_year: 2023,
                completion_date_actual: new Date('2023-11-20'),
                contractor_id: null,
                contractor_name: 'RELIABLE FLOOD CONTROL SERVICES',
                status: 'finished',
                risk_score: 18,
                is_flagged: false
            },
            {
                region: 'Region VIII',
                legislative_district: 'LEYTE (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Leyte 1st District Engineering Office',
                project_id: 'P00876543HH',
                project_name: 'Ormoc River Flood Control',
                type_of_work: 'Drainage System Improvement',
                infrastructure_type: 'Flood Control Structures',
                longitude: 124.60417000,
                latitude: 11.00611000,
                contract_id: '23EG0045',
                approved_budget: 38000000,
                contract_cost: 37200000,
                start_date: new Date('2023-02-15'),
                funding_year: 2023,
                completion_date_actual: new Date('2023-10-30'),
                contractor_id: null,
                contractor_name: 'RELIABLE FLOOD CONTROL SERVICES',
                status: 'finished',
                risk_score: 15,
                is_flagged: false
            },
            {
                region: 'Region IX',
                legislative_district: 'ZAMBOANGA DEL NORTE (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Zamboanga del Norte 1st District Engineering Office',
                project_id: 'P00765432II',
                project_name: 'Dipolog Flood Control Structure',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 123.34306000,
                latitude: 8.58917000,
                contract_id: '21EG0066',
                approved_budget: 50000000,
                contract_cost: 28000000,
                start_date: new Date('2021-05-01'),
                funding_year: 2021,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'SUSPICIOUS INFRASTRUCTURE GROUP',
                status: 'ongoing',
                risk_score: 96,
                is_flagged: true
            },
            {
                region: 'Region IX',
                legislative_district: 'ZAMBOANGA DEL NORTE (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Zamboanga del Norte 1st District Engineering Office',
                project_id: 'P00654321JJ',
                project_name: 'Dapitan River Channel Improvement',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 123.41194000,
                latitude: 8.65556000,
                contract_id: '22EG0033',
                approved_budget: 45000000,
                contract_cost: 22000000,
                start_date: new Date('2022-02-10'),
                funding_year: 2022,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'SUSPICIOUS INFRASTRUCTURE GROUP',
                status: 'ongoing',
                risk_score: 94,
                is_flagged: true
            },
            {
                region: 'Region X',
                legislative_district: 'MISAMIS ORIENTAL (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Misamis Oriental 1st District Engineering Office',
                project_id: 'P00543210KK',
                project_name: 'Cagayan de Oro Flood Control Wall',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 124.63722000,
                latitude: 8.48222000,
                contract_id: '20EG0099',
                approved_budget: 60000000,
                contract_cost: 25000000,
                start_date: new Date('2020-01-15'),
                funding_year: 2020,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'GHOST PROJECT CONSTRUCTION',
                status: 'ongoing',
                risk_score: 100,
                is_flagged: true
            },
            {
                region: 'Region XI',
                legislative_district: 'DAVAO DEL SUR (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Davao del Sur 1st District Engineering Office',
                project_id: 'P00432109LL',
                project_name: 'Davao River Flood Control Phase 1',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 125.60806000,
                latitude: 7.07167000,
                contract_id: '22EG0066',
                approved_budget: 52000000,
                contract_cost: 50800000,
                start_date: new Date('2022-04-01'),
                funding_year: 2022,
                completion_date_actual: new Date('2022-12-20'),
                contractor_id: null,
                contractor_name: 'TRUSTWORTHY BUILDERS PH',
                status: 'finished',
                risk_score: 12,
                is_flagged: false
            },
            {
                region: 'Region VIII',
                legislative_district: 'LEYTE (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Leyte 1st District Engineering Office',
                project_id: 'P00321098MM',
                project_name: 'Baybay Flood Control Structure',
                type_of_work: 'Drainage System Improvement',
                infrastructure_type: 'Flood Control Structures',
                longitude: 124.79833000,
                latitude: 10.67750000,
                contract_id: '23EG0046',
                approved_budget: 35000000,
                contract_cost: 34200000,
                start_date: new Date('2023-03-01'),
                funding_year: 2023,
                completion_date_actual: new Date('2023-11-10'),
                contractor_id: null,
                contractor_name: 'RELIABLE FLOOD CONTROL SERVICES',
                status: 'finished',
                risk_score: 16,
                is_flagged: false
            },
            {
                region: 'Region VIII',
                legislative_district: 'LEYTE (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Leyte 1st District Engineering Office',
                project_id: 'P00210987NN',
                project_name: 'Carigara River Flood Control',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 124.67694000,
                latitude: 11.29722000,
                contract_id: '23EG0047',
                approved_budget: 42000000,
                contract_cost: 40800000,
                start_date: new Date('2023-04-15'),
                funding_year: 2023,
                completion_date_actual: new Date('2023-12-05'),
                contractor_id: null,
                contractor_name: 'RELIABLE FLOOD CONTROL SERVICES',
                status: 'finished',
                risk_score: 14,
                is_flagged: false
            },
            {
                region: 'Region VIII',
                legislative_district: 'SAMAR (SECOND LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Samar 2nd District Engineering Office',
                project_id: 'P00109876OO',
                project_name: 'Calbayog Flood Control Structure',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 124.59583000,
                latitude: 12.06778000,
                contract_id: '22EG0056',
                approved_budget: 48000000,
                contract_cost: 46500000,
                start_date: new Date('2022-05-01'),
                funding_year: 2022,
                completion_date_actual: new Date('2023-01-15'),
                contractor_id: null,
                contractor_name: 'RELIABLE FLOOD CONTROL SERVICES',
                status: 'finished',
                risk_score: 19,
                is_flagged: false
            },
            {
                region: 'Region VIII',
                legislative_district: 'SAMAR (SECOND LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Samar 2nd District Engineering Office',
                project_id: 'P00098765PP',
                project_name: 'Catbalogan River Channel Improvement',
                type_of_work: 'Drainage System Improvement',
                infrastructure_type: 'Flood Control Structures',
                longitude: 124.88333000,
                latitude: 11.77500000,
                contract_id: '23EG0048',
                approved_budget: 38000000,
                contract_cost: 36800000,
                start_date: new Date('2023-05-20'),
                funding_year: 2023,
                completion_date_actual: new Date('2023-12-18'),
                contractor_id: null,
                contractor_name: 'RELIABLE FLOOD CONTROL SERVICES',
                status: 'finished',
                risk_score: 17,
                is_flagged: false
            },
            {
                region: 'Region VIII',
                legislative_district: 'SAMAR (SECOND LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Samar 2nd District Engineering Office',
                project_id: 'P00987654QQ',
                project_name: 'Basey Flood Control Project',
                type_of_work: 'Drainage System Improvement',
                infrastructure_type: 'Flood Control Structures',
                longitude: 125.06806000,
                latitude: 11.27778000,
                contract_id: '24EG0011',
                approved_budget: 35000000,
                contract_cost: 34200000,
                start_date: new Date('2024-01-15'),
                funding_year: 2024,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'RELIABLE FLOOD CONTROL SERVICES',
                status: 'ongoing',
                risk_score: 22,
                is_flagged: false
            },
            {
                region: 'Region IX',
                legislative_district: 'ZAMBOANGA DEL NORTE (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Zamboanga del Norte 1st District Engineering Office',
                project_id: 'P00876543RR',
                project_name: 'Polanco Flood Control Structure',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 123.36583000,
                latitude: 8.53333000,
                contract_id: '22EG0034',
                approved_budget: 42000000,
                contract_cost: 21000000,
                start_date: new Date('2022-03-20'),
                funding_year: 2022,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'SUSPICIOUS INFRASTRUCTURE GROUP',
                status: 'ongoing',
                risk_score: 93,
                is_flagged: true
            },
            {
                region: 'Region IX',
                legislative_district: 'ZAMBOANGA DEL NORTE (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Zamboanga del Norte 1st District Engineering Office',
                project_id: 'P00765432SS',
                project_name: 'Roxas Flood Control Wall',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 123.28889000,
                latitude: 8.48889000,
                contract_id: '23EG0022',
                approved_budget: 38000000,
                contract_cost: 19000000,
                start_date: new Date('2023-01-10'),
                funding_year: 2023,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'SUSPICIOUS INFRASTRUCTURE GROUP',
                status: 'ongoing',
                risk_score: 95,
                is_flagged: true
            },
            {
                region: 'Region IX',
                legislative_district: 'ZAMBOANGA DEL NORTE (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Zamboanga del Norte 1st District Engineering Office',
                project_id: 'P00654321TT',
                project_name: 'Sindangan River Channel Project',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 123.00194000,
                latitude: 8.23750000,
                contract_id: '23EG0023',
                approved_budget: 45000000,
                contract_cost: 27000000,
                start_date: new Date('2023-04-01'),
                funding_year: 2023,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'SUSPICIOUS INFRASTRUCTURE GROUP',
                status: 'ongoing',
                risk_score: 92,
                is_flagged: true
            },
            {
                region: 'Region IX',
                legislative_district: 'ZAMBOANGA DEL NORTE (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Zamboanga del Norte 1st District Engineering Office',
                project_id: 'P00543210UU',
                project_name: 'Siayan Flood Control Structure',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 123.10556000,
                latitude: 8.26667000,
                contract_id: '24EG0022',
                approved_budget: 40000000,
                contract_cost: 24000000,
                start_date: new Date('2024-02-01'),
                funding_year: 2024,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'SUSPICIOUS INFRASTRUCTURE GROUP',
                status: 'ongoing',
                risk_score: 91,
                is_flagged: true
            },
            {
                region: 'Region X',
                legislative_district: 'MISAMIS ORIENTAL (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Misamis Oriental 1st District Engineering Office',
                project_id: 'P00432109VV',
                project_name: 'Iligan Flood Control Structure',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 124.24306000,
                latitude: 8.22889000,
                contract_id: '20EG0100',
                approved_budget: 58000000,
                contract_cost: 24000000,
                start_date: new Date('2020-03-01'),
                funding_year: 2020,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'GHOST PROJECT CONSTRUCTION',
                status: 'ongoing',
                risk_score: 100,
                is_flagged: true
            },
            {
                region: 'Region X',
                legislative_district: 'MISAMIS ORIENTAL (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Misamis Oriental 1st District Engineering Office',
                project_id: 'P00321098WW',
                project_name: 'Gingoog River Flood Control',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 125.10278000,
                latitude: 8.82444000,
                contract_id: '21EG0044',
                approved_budget: 52000000,
                contract_cost: 26000000,
                start_date: new Date('2021-01-20'),
                funding_year: 2021,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'GHOST PROJECT CONSTRUCTION',
                status: 'ongoing',
                risk_score: 99,
                is_flagged: true
            },
            {
                region: 'Region X',
                legislative_district: 'MISAMIS ORIENTAL (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Misamis Oriental 1st District Engineering Office',
                project_id: 'P00210987XX',
                project_name: 'El Salvador Flood Control Wall',
                type_of_work: 'River Channel Improvement',
                infrastructure_type: 'Flood Control Structures',
                longitude: 124.52111000,
                latitude: 8.56389000,
                contract_id: '21EG0045',
                approved_budget: 45000000,
                contract_cost: 22500000,
                start_date: new Date('2021-04-15'),
                funding_year: 2021,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'GHOST PROJECT CONSTRUCTION',
                status: 'ongoing',
                risk_score: 98,
                is_flagged: true
            },
            {
                region: 'Region X',
                legislative_district: 'MISAMIS ORIENTAL (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Misamis Oriental 1st District Engineering Office',
                project_id: 'P00109876YY',
                project_name: 'Tagoloan River Channel Improvement',
                type_of_work: 'River Channel Improvement',
                infrastructure_type: 'Flood Control Structures',
                longitude: 124.75417000,
                latitude: 8.54167000,
                contract_id: '22EG0022',
                approved_budget: 48000000,
                contract_cost: 24000000,
                start_date: new Date('2022-02-01'),
                funding_year: 2022,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'GHOST PROJECT CONSTRUCTION',
                status: 'ongoing',
                risk_score: 97,
                is_flagged: true
            },
            {
                region: 'Region X',
                legislative_district: 'MISAMIS ORIENTAL (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Misamis Oriental 1st District Engineering Office',
                project_id: 'P00098765ZZ',
                project_name: 'Villanueva Flood Control Structure',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 124.77833000,
                latitude: 8.58889000,
                contract_id: '23EG0011',
                approved_budget: 42000000,
                contract_cost: 21000000,
                start_date: new Date('2023-01-15'),
                funding_year: 2023,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'GHOST PROJECT CONSTRUCTION',
                status: 'ongoing',
                risk_score: 96,
                is_flagged: true
            },
            {
                region: 'Region X',
                legislative_district: 'MISAMIS ORIENTAL (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Misamis Oriental 1st District Engineering Office',
                project_id: 'P00987654AAA',
                project_name: 'Claveria Flood Control Project',
                type_of_work: 'River Channel Improvement',
                infrastructure_type: 'Flood Control Structures',
                longitude: 124.90278000,
                latitude: 8.61000000,
                contract_id: '23EG0012',
                approved_budget: 38000000,
                contract_cost: 19000000,
                start_date: new Date('2023-05-01'),
                funding_year: 2023,
                completion_date_actual: null,
                contractor_id: null,
                contractor_name: 'GHOST PROJECT CONSTRUCTION',
                status: 'ongoing',
                risk_score: 95,
                is_flagged: true
            },
            {
                region: 'Region XI',
                legislative_district: 'DAVAO DEL SUR (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Davao del Sur 1st District Engineering Office',
                project_id: 'P00876543BBB',
                project_name: 'Davao River Flood Control Phase 2',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 125.61528000,
                latitude: 7.07500000,
                contract_id: '23EG0022',
                approved_budget: 55000000,
                contract_cost: 53800000,
                start_date: new Date('2023-01-20'),
                funding_year: 2023,
                completion_date_actual: new Date('2023-11-30'),
                contractor_id: null,
                contractor_name: 'TRUSTWORTHY BUILDERS PH',
                status: 'finished',
                risk_score: 10,
                is_flagged: false
            },
            {
                region: 'Region XI',
                legislative_district: 'DAVAO DEL SUR (FIRST LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Davao del Sur 1st District Engineering Office',
                project_id: 'P00765432CCC',
                project_name: 'Digos Flood Control Structure',
                type_of_work: 'Drainage System Improvement',
                infrastructure_type: 'Flood Control Structures',
                longitude: 125.35722000,
                latitude: 6.74917000,
                contract_id: '23EG0023',
                approved_budget: 48000000,
                contract_cost: 46800000,
                start_date: new Date('2023-03-01'),
                funding_year: 2023,
                completion_date_actual: new Date('2023-12-10'),
                contractor_id: null,
                contractor_name: 'TRUSTWORTHY BUILDERS PH',
                status: 'finished',
                risk_score: 11,
                is_flagged: false
            },
            {
                region: 'Region XI',
                legislative_district: 'DAVAO DEL NORTE (SECOND LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Davao del Norte 2nd District Engineering Office',
                project_id: 'P00654321DDD',
                project_name: 'Tagum Flood Control Structure',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 125.81083000,
                latitude: 7.44833000,
                contract_id: '22EG0067',
                approved_budget: 50000000,
                contract_cost: 48800000,
                start_date: new Date('2022-05-15'),
                funding_year: 2022,
                completion_date_actual: new Date('2022-12-28'),
                contractor_id: null,
                contractor_name: 'TRUSTWORTHY BUILDERS PH',
                status: 'finished',
                risk_score: 9,
                is_flagged: false
            },
            {
                region: 'Region XI',
                legislative_district: 'DAVAO DEL NORTE (SECOND LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Davao del Norte 2nd District Engineering Office',
                project_id: 'P00543210EEE',
                project_name: 'Panabo River Channel Improvement',
                type_of_work: 'Drainage System Improvement',
                infrastructure_type: 'Flood Control Structures',
                longitude: 125.68333000,
                latitude: 7.30833000,
                contract_id: '23EG0024',
                approved_budget: 45000000,
                contract_cost: 43800000,
                start_date: new Date('2023-04-10'),
                funding_year: 2023,
                completion_date_actual: new Date('2023-11-25'),
                contractor_id: null,
                contractor_name: 'TRUSTWORTHY BUILDERS PH',
                status: 'finished',
                risk_score: 10,
                is_flagged: false
            },
            {
                region: 'Region XI',
                legislative_district: 'DAVAO DEL NORTE (SECOND LEGISLATIVE DISTRICT)',
                district_engineering_office: 'Davao del Norte 2nd District Engineering Office',
                project_id: 'P00432109FFF',
                project_name: 'Mati Flood Control Structure',
                type_of_work: 'Construction of Flood Mitigation Structure',
                infrastructure_type: 'Flood Control Structures',
                longitude: 126.21528000,
                latitude: 6.94806000,
                contract_id: '23EG0025',
                approved_budget: 52000000,
                contract_cost: 50800000,
                start_date: new Date('2023-06-01'),
                funding_year: 2023,
                completion_date_actual: new Date('2023-12-15'),
                contractor_id: null,
                contractor_name: 'TRUSTWORTHY BUILDERS PH',
                status: 'finished',
                risk_score: 8,
                is_flagged: false
            }
        ];

        const createdProjects = await Project.insertMany(projects);

        for (const project of createdProjects) {
            const contractor = await Contractor.findOne({ company_name: project.contractor_name });
            if (contractor) {
                if (!contractor.contract_ids.includes(project.contract_id)) {
                    contractor.contract_ids.push(project.contract_id);
                }
                if (!contractor.projects.includes(project._id)) {
                    contractor.projects.push(project._id);
                }
                project.contractor_id = contractor._id;
                await contractor.save();
                await project.save();
            }
        }

        console.log(`${createdProjects.length} projects seeded successfully`);
        return createdProjects;
    } catch (error) {
        console.error('Error seeding projects:', error);
        throw error;
    }
};

export default seedProjects;

